# Generated by Django 5.0.7 on 2024-08-12 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Learn_Linguo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="reference_text",
            new_name="answer",
        ),
        migrations.AddField(
            model_name="assignment",
            name="question",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
